### PR TITLE
Add Chinese numbers

### PR DESCRIPTION
**Pull request by BLKSerene**
The first 10 Chinese characters added are "lowercase" Chinese numbers (representing 0, 1, 2, ..., 9) and the other 10 are "uppercase" ones, so 20 characters in total.

Another question is that Chinese also has characters for 10 (十/拾), 100 (百/佰), 1,000 (千/仟), 10,000 (万/萬), 100,000,000 (亿/億)， should I also add these as numbers?

Reference: https://en.wikipedia.org/wiki/Chinese_numerals#Standard_numbers

\* The added Chinese numbers are all written in Simplified Chinese rather than Traditional Chinese, since the Chinese stop words currently included in this package are all simplified ones.
\*\* I mainly use Python these days and haven't worked with JS for a long time. Hope that I get these JS codes right...

### CODE REVIEW

**Comment by eklem** [comment]
Really nice work, but I am a little bit unsure on what to do. The reason I originaly took the numbers out was that regexp in JavaScript got the unicode property escapes added, so we can now identify words and numbers and differentiate between them for most languages in the world. This means a user can extract only words from a text and then remove the stopwords.

Then the numbers written with ciphers could be removed from the langauge stopword lists. But I've kept the numbers written with letters. This is for the numbers 0-9 because they mostly don't meen that much, but higher numbers mostly have a meaning. For people still wanting to remove 0-9 I have added the _123-list as an alternative, if my change didn't fit their need.

I checked and these numbers are identified as words by a unicode property escape regexp (images). So, from a regexp point of view, we should rather add them to the Chinese simplified word list, rather than the _123-list.

What do you think?

**Comment by BLKSerene** [comment]
For consistency and easy maintenance, I think only 0-9 should be included and larger numbers should be excluded.

But I'm not sure what you mean by "unicode property escape regexp (images)"? Do you mean unicode characters whose `Numeric_Type `is `Decimal`? If this is the case, then it makes sense. The number lists should follow Unicode standards to achieve consistency: https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=[:Numeric_Type=Decimal:]

So, I suggest:
1. Since Chinese numerals are not on the above list, they should be added directly to the Chinese stop word list.
2. Numbers listed in `numKor` are all full-width digits, but they are not used in Korean exclusively. All CJK languages would use full-width digits to achieve typographic consistency (since, for example, Chinese characters are full-width characters), though half-width ones are more commonly-used. And full-width digits are also used in Western languages (by mistake sometimes).
3. Browsing the above list, numerals of several languages are missing: Arabic (Arabic-Indic digits / Eastern Arabic-Indic digits), Bengali, Punjabi Gurmukhi, Gujarati, Thai, Myanmar (Shan digits / Tai Laing digits)
4. Telegu numbers are already included in numTel, but there are no Telugu stop words currently. This is a minor issue, no harm to include them though.

**Comment by BLKSerene** [comment]
In Python, both
`'一'.isnumeric() # Lowercase Chinese number 1`
and
`'壹'.isnumeric() # Uppercase Chinese number 1`
return `True` (using the standard library `re`), since any Unicode character whose `Numeric_Type` equals `Digit`, `Decimal`, or `Numeric` would be counted as a numeral: https://docs.python.org/3/library/stdtypes.html#str.isnumeric

I'm not sure how regex matching is implemented in JS. Which standard should be followed?

**Comment by eklem** [comment]
It seems they are all defined as letters/words in JavaScript, except for zero - `〇`. I'll look a bit more into it.

**Comment by eklem** [comment]
Ok, this took a while. I'll check a bit more, but then, if it is like I suspect, I'll have to go with the JavaScript way of implementing this.

**Pull request closed without merging**
