### PR TITLE
Fix 19, 16, 17 numbers - porBr

### PR DESCRIPTION
**Pull request by rodfeal**
I've noticed some numbers in the Brazilian Portuguese stopwords has been using the Portuguese (European) version, so I'm sending this PR to fix them, as it's not the same between these languages.

<table>
<tr>
<th>Number</th>
<th>por</th>
<th>porBr</th>
</tr>
<tr>
<th>19</th>
<th>Dezanove</th>
<th>Dezenove</th>
</tr>
<tr>
<th>16</th>
<th>Dezasseis</th>
<th>Dezesseis</th>
</tr>
<tr>
<th>17</th>
<th>Dezassete</th>
<th>Dezessete</th>
</tr>
</table>

I've looked through the entire list of words and I just noticed these three that should get fixed.

Reply me if you need some help, or if I've done something wrong!

### CODE REVIEW

**Comment by eklem** [comment]
Nice! Thanks a lot, @rodfeal

**Comment by eklem** [comment]
@rodfeal I'll publish a new NPM-version when I get the tests working. For some reason, they break on v18. It seems like a test-setup problem. Not sure what changed between v16 and v18.

**Comment by eklem** [comment]
Ok, skipped tests for NodeJS v18.x for now, will come back to that later.

**Comment by rodfeal** [comment]
> Ok, skipped tests for NodeJS v18.x for now, will come back to that later.

Oh don't worry! And thanks a lot for the quick response.
I may try something about fixing this bug when I've got some time, meanwhile I agree I think it's ok to skip them.

Thanks again

**Comment by eklem** [comment]
Seems to be some AvaJS-issue with NodeJS v18.8.0. Tried NodeJS v18.7.0 and that worked fine. Guessing waiting a little will do the trick 😄

**Comment by eklem** [comment]
I just need to update test-framework to have latest AvaJS, and it will be okay I think. I'll do that tomorrow. Thanks for the valuable input and PR!

**Comment by eklem** [comment]
Now all tests are working, added Node 18.x to workflow/test.yml

**Pull request merged**
