### PR TITLE
Update stopwords_ukr.js

### PR DESCRIPTION
**Pull request by imposeren**
Manually selected top frequency pronounces, conjunctions, adpositions, grammatical particles and adverbs from Ukrainian corpus and added them to stopwords_ukr.js . Also moved some stopwords from the end of the list to their alphabetical position: now whole list is more or less in alphabetical order (first letter for sure, second letter I think is also fine, but I did not check all existing words and did not use automatic sorting to minimize the changes)

### CODE REVIEW

**Comment by eklem** [comment]
Nice, thanks @imposerene!
I need the tests to run again, and then I'll publish to NPM.

**Comment by imposeren** [comment]
Sorry, pushed some more changes. I think that's all for now. But yeah, I saw that tests failed before I pushed again... Will look at what fails and try to fix (maybe I just missed coma somewhere)

**Comment by imposeren** [comment]
Sorry. Used wrong email in my commit (was using work one). Amended to not relate my current company to the commit. Sorry, for slopy commits...

**Comment by eklem** [comment]
No problem 😊

**Comment by imposeren** [comment]
Any suggestions on how to quickly run tests locally? I'm not a JS developer, but if there is an easy way to run under linux or in docker, then I can manage to check the tests locally. I already pushed potential fix (test will now expect "на" adposition to be removed), but would be greate if I could actually run the test locally

**Comment by imposeren** [comment]
All tests are ok after the small fix I introduced earlier

**Comment by eklem** [comment]
All tests worked now! So I'll merge and publish!

**Comment by eklem** [comment]
New version out on npm: https://www.npmjs.com/package/stopword/v/3.1.2
... and here too: https://github.com/fergiemcdowall/stopword/releases/tag/v3.1.2

Thanks for the PR, @imposeren !

**Pull request merged**
