### PR TITLE
Added optional case sensitive key

### PR DESCRIPTION
**Pull request by harut17harut**

### CODE REVIEW

**Comment by eklem** [comment]
Hi @harut17harut,
What's the usecase?

Also, I think we need the standard to be:
`const removeStopwords = function (tokens, stopwords, options = { caseSensitive: true }) {`
... and the 3rd party license-file back since it's distributed through CDNs.

**Comment by eklem** [comment]
Hi @harut17harut 
What is your use case for this? Just trying to understand it and also if the default should be setting it lowercase to true.

**Comment by harut17harut** [comment]
Hi,there are some words, for example dry which i need to extract from text,
but DRY must not be deleted,i am using your package to extract keywords
from text,for that case i need to have option of case sensitivity

пт, 3 мар. 2023 г. в 17:55, Espen Klem ***@***.***>:

**Comment by eklem** [comment]
But then you would also not remove the word dry when it comes first in a sentence?

**Comment by eklem** [comment]
I'm not sure how to solve your issue, but I don't think this will be a good one.

**Pull request closed without merging**
