### PR TITLE
feat: add language select to demo

### LINKED ISSUE #81: Add all languages to the Demo

### PR DESCRIPTION
**Pull request by arthurdenner**
Hi! 👋🏽 

This PR tries to improve the demo by listing all available languages - parsing it from the `sw` global variable.

It feels a bit hacky but I decided to propose it for the sake of simplicity.

Let me know what you think, if I changed too much or if you find any bugs.

Closes #81.

### CODE REVIEW

**Review by eklem — APPROVED** [review]
Seems good!

**Comment by eklem** [comment]
Great work, @arthurdenner! Thank you =)
Just did some small adjustments to the HTML, making it look a bit more like [another demo](https://eklem.github.io/daq-proc/demo/document-processing/) in the same type of tools.

**Comment by arthurdenner** [comment]
Cool, thanks!

**Comment by eklem** [comment]
And a little hack'ish must be allowed in a demo =)

**Comment by fergiemcdowall** [comment]
@arthurdenner code looks good- not too hacky at all! nice PR! 👍

**Pull request merged**
