### PR TITLE
countries and other words

### PR DESCRIPTION
**Pull request by cheezeburger**

### CODE REVIEW

**Comment by eklem** [comment]
Maybe we could keep the spread syntax (but leave the countries out)?

**Comment by eklem** [comment]
Sorry, on my phone it looked like a PR for the original repository. Don't mind me =)

**Comment by cheezeburger** [comment]
Hi Eklem, thanks for following. I originally wanted to push to my own fork but accidentally submitted a PR to your repo. 

It was a very specific change so I closed the PR.

The spread syntax would be nice in combination with the functionality that allows user to add their own stopwords to the default one, instead of choosing between default or fully custom sw.

**Comment by eklem** [comment]
A fantastic solution. I've been thinking about this for a while, but didn't think there were any clean, nicely degradable solutions.

**Comment by eklem** [comment]
Finally got around to look at this. It's possible with existing code. Just to combine several arrays with spread syntax (both predefined and custom). Thanks for the idea, @cheezeburger =)

**Comment by cheezeburger** [comment]
@eklem You're welcome!

**Pull request closed without merging**
