### PR TITLE
Added indonesia

### PR DESCRIPTION
**Pull request by hifiaz**
i have remove some word in this pull request

### CODE REVIEW

**Comment by eklem** [comment]
Great! Are you able to add a test for it too?

**Comment by hifiaz** [comment]
wait I'll make it, sorry I'm new to the open source project

**Comment by eklem** [comment]
No problem @hifiaz . I can make it too, and then you can verify it, if that's okay?

**Comment by hifiaz** [comment]
> No problem @hifiaz . I can make it too, and then you can verify it, if that's okay?

its okey, no problem, i will verify it

**Comment by eklem** [comment]
@hifiaz Does this test look correct to you?
https://github.com/fergiemcdowall/stopword/blob/master/test/test.js#L215-L219

**Comment by hifiaz** [comment]
> @hifiaz Does this test look correct to you?
> https://github.com/fergiemcdowall/stopword/blob/master/test/test.js#L215-L219

yeah great! thank you

**Comment by eklem** [comment]
Super! Thanks for the pullrequest, @hifiaz =)

**Pull request merged**
